/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const amm_calculator_init: (a: number, b: number) => void;
export const systeminstruction_advanceNonceAccount: (a: number, b: number) => number;
export const systeminstruction_allocate: (a: number, b: bigint) => number;
export const systeminstruction_allocateWithSeed: (a: number, b: number, c: number, d: number, e: bigint, f: number) => number;
export const systeminstruction_assign: (a: number, b: number) => number;
export const systeminstruction_assignWithSeed: (a: number, b: number, c: number, d: number, e: number) => number;
export const systeminstruction_authorizeNonceAccount: (a: number, b: number, c: number) => number;
export const systeminstruction_createAccount: (a: number, b: number, c: bigint, d: bigint, e: number) => number;
export const systeminstruction_createAccountWithSeed: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: bigint, h: number) => number;
export const systeminstruction_createNonceAccount: (a: number, b: number, c: number, d: bigint) => any;
export const systeminstruction_transfer: (a: number, b: number, c: bigint) => number;
export const systeminstruction_transferWithSeed: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => number;
export const systeminstruction_withdrawNonceAccount: (a: number, b: number, c: number, d: bigint) => number;
export const __wbg_instruction_free: (a: number, b: number) => void;
export const __wbg_instructions_free: (a: number, b: number) => void;
export const instructions_constructor: () => number;
export const instructions_push: (a: number, b: number) => void;
export const __wbg_pubkey_free: (a: number, b: number) => void;
export const pubkey_constructor: (a: any) => [number, number, number];
export const pubkey_createProgramAddress: (a: number, b: number, c: number) => [number, number, number];
export const pubkey_createWithSeed: (a: number, b: number, c: number, d: number) => [number, number, number];
export const pubkey_equals: (a: number, b: number) => number;
export const pubkey_findProgramAddress: (a: number, b: number, c: number) => [number, number, number];
export const pubkey_isOnCurve: (a: number) => number;
export const pubkey_toBytes: (a: number) => [number, number];
export const pubkey_toString: (a: number) => [number, number];
export const __wbg_hash_free: (a: number, b: number) => void;
export const hash_constructor: (a: any) => [number, number, number];
export const hash_equals: (a: number, b: number) => number;
export const hash_toBytes: (a: number) => [number, number];
export const hash_toString: (a: number) => [number, number];
export const wasm_bindgen__closure__destroy__h98aa70fa03c06cf9: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2bbc4d1c8f5e0468: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
